[package]
name = "library_rust"
version = "0.1.0"
authors = ["bl0rch1d <temaflash96@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
